# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

jobs:
  - job: Nuget
    pool:
      vmImage: 'windows-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: GitVersion@4
      inputs:
        updateAssemblyInfo: true

    - script: dotnet build --configuration $(buildConfiguration) -p:PackageVersion=$(GitVersion.FullSemVer) src/SmartHomeDotNet.sln
      displayName: 'dotnet build $(buildConfiguration)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'src/SmartHomeDotNet.Package/bin/$(buildConfiguration)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/Nuget/Package'

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Nuget'
        ArtifactName: 'Nuget'
        publishLocation: 'Container'

  - job: Docker_Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: GitVersion@4
      inputs:
        updateAssemblyInfo: true

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: CmdLine@2
      inputs:
        script: |
          echo ##vso[task.setvariable variable=GitVersion.SemVer]$(GitVersion.SemVer) >> "$(Build.ArtifactStagingDirectory)\config.txt"
          docker build src/. -t smarthomedotnet:$(Build.BuildId)
          docker save smarthomedotnet:$(Build.BuildId) -o "$(Build.ArtifactStagingDirectory)\smarthomedotnet-$(Build.BuildId)-win.tar"

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Docker-Windows'
        publishLocation: 'Container'

  - job: Docker_Linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    # As of 2019/07/18 GitVersion is failing on Linux, even with v5.0.0.-beta5-9
    # - task: GitVersion@4
    #   inputs:
    #     updateAssemblyInfo: true

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: CmdLine@2
      inputs:
        # echo ##vso[task.setvariable variable=GitVersion.SemVer]$(GitVersion.SemVer) >> "$(Build.ArtifactStagingDirectory)/config.txt"
        script: |
          docker build src/. -t smarthomedotnet:$(Build.BuildId)
          docker save smarthomedotnet:$(Build.BuildId) -o "$(Build.ArtifactStagingDirectory)/smarthomedotnet-$(Build.BuildId)-linux.tar"

    - task: PublishBuildArtifacts@1
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Docker-Linux'
        publishLocation: 'Container'
