using System;
using System.Linq;
using Mavri.Ha.Generation;

namespace HomeGenerator.Cli.Utils;

internal static class CodeGenToolExtensions
{
	public static string GetCodeGenAttribute(this ICodeGenTool tool)
		=> $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{tool.GetType().Name}"", ""{tool.Version}"")]";

	public static string GetFileHeader(this ICodeGenTool tool, int aligned = 0)
		=> $@"//----------------------
		// <auto-generated>
		//	Generated by the {tool.GetType().Name} v{tool.Version}. DO NOT EDIT!
		//	Manual changes to this file will be overwritten if the code is regenerated.
		// </auto-generated>
		//----------------------
		#pragma warning disable
		#nullable enable".Align(Math.Max(aligned - 1, 0));
}